spring:
  output.ansi.enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: demo
    password: root
  jpa:
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:/scripts
application:
  files:
    product: 'product.csv'
    size: 'size.csv'
    stock: 'stocks.csv'